# Quantum Anomaly in 1+1d QFT

In this chapter we learn about quantum anomaly of symmetry in 1+1-dimensional QFT. A QFT is a quantum mechanics equipped with a continuous locality (while a lattice system possess a discrete locality).[^QFTvsLattice] Here, the locality means that we have the notion of "space", and the observables are contained in the space.
This locality (plus some assumption) prohibits the projective phase that we discussed so far, but then there is possibly more subtle anomaly about how much local the composition law of the symmetry is.
It is not a very traditional way but we see this phenomenon through the action of the symmetry on the Hilbert spaces of QFT on *an interval* with different boundary conditions. The quantum anomaly in this dimensions for a finite group $G$ can be captured by the 3rd group cohomology.

[^QFTvsLattice]: Most things in this chapter are supposed to be applied to both of QFTs and lattice systems. It is just that KO is more familiar with QFTs and also the lecture is for high-energy students.


## QFT on a manifold and symmetry
As emphasized, the locality plays the essential role in (topological properties of) QFT.
One concequence of the locality is that,
given a $d+1$-dimensional QFT, we can quantize the theoy on a spacial closed manifold $M_d$ to get $\mathcal{H}_{M_d}$.[^structure]
In other words a QFT is not just the Hilbert space and the Hamiltonian, but a rule to assign them when a closed manifold $M_d$ is given.
It is more precise to express the same thing in terms of the algebra of operators. 
For a QFT, given a region $R \in \mathbb{R}^{d,1}$, there is the algebra of local operators contained in $R$: $\mathcal{A}(R)$.
Then we "glue" the algebra $\mathcal{A}(B^{d+1})$ on a ball to get $\mathcal{A}(R)$ for an arbitrary manifold $R$. In particular we can get $\mathcal{A}(M_d\times \mathbb{R})$.[^rough]

[^rough]: This explanation is awfully rough. For a better discussion the reader might refer to @Witten:2021jzq

A symmetry also is expected to be local: that if there is a symmetry $T$ in a QFT, that means, for arbitrary $\mathcal{M}_d$,
there should exists a symmetry transformation $T_{M_d}$ on $\mathbb{P}\mathcal{H}_{M_d}$.
This is manifest in the case of continuous symmetry. 
For example, the unitary operator $U_\lambda$ for a $U(1)$ rotation by angle $\lambda$ is, from the Noether's theorem,
\begin{equation}
    (\#eq:Noether)
    U_\alpha = e^{\mathrm{i}\lambda \int_{M_d}j^0 \mathrm{d}^dx},
\end{equation}
where $j^\mu$ is the Noether current. 
In other words the locality of the unitary operator is manifest in the integral in the expression.
For a discrete symmetry, the Noether current is not available. 
However, we can define that a symmetry transformation is a automorphism of $\mathcal{A}(R)$:
\begin{equation}
    (\#eq:TonAR)
    T \curvearrowright \mathcal{A}(R) \to \mathcal{A}(R),
\end{equation}
and then $T$ also naturally (projectively) acts on $\mathcal{H}_{M_d}$ which is a representation of $\mathcal{A}(R)$.
In a more explict term, if the QFT is written in terms of fundamental fields and symmetry acts on these fields,
the Hilbert space $\mathcal{H}_{M_d}$ is the Fock space constructed from creation/annhilation operators for each modes of the fields on $M_d$,
and the action of a symmetry on the fields naturally defines the action on the annihilation operators, in turn defining the action on $\mathcal{H}_{M_d}$.

For a local symmetry transformation $T$, defined in the above sense, to be the symmetry of the theory, the corresponding unitary has to commute with the Hamiltonian.
We also assume that the Hamiltonian is local:
\begin{equation}
    (\#eq:localHam)
    H = \int T_{00} \mathrm{d}^dx,
\end{equation}
where $T_{\mu\nu}$ is the energy-momentum tensor.
For a symmetry in QFT, we demand that $[U,T_{\mu\nu}] = 0$. Otherwise $U$ does not commute with the spacetime symmetry.


[^structure]: We often need an additional structure to $M_d$. For example, if the theory includes fermionic fields, the manifold $M_d$ has to be equipped with the spin structure. In this lecture we do not care about thie subtle but interesting and important subtlety and assume that the theory is *bosonic*, i.e. does not contain fermionic fields. This amounts to assume only the orientation of $M_d$. (To put a QFT on an unoriented manifold, one needs an anti-unitary symmetry which also be ignored in thie lecture.) The references mentioned in \@ref(othernotes) have contents about fermionic theories.

## No projective phase on S^1{#noproj}
Now specialize to 1+1d QFT, and consider $M_1 = S^1$, which is the only connected closed 1-dimensional manifold.
A reader might have guessed that, as a generalization of what we have learned in the case of QM, the unitary operator realizing the symmetry on $\mathcal{H}_{S^1}$ might have projective phase in there multiplication rule.
This very natural guess, however, is not correct.

For a general QFT, the Hamiltonian depends on the radius $R$ of $S^1$.
When $R$ is very large compared to any scale in the theory, we regard the QFT on $S^1\times \mathbb{R}_\text{time}$ as the infrared-regulation of QFT on $\mathbb{R}^1\times \mathbb{R}_\text{time}$.

Now, if the QFT has single vacuum, the cluster decomposition principle (which is another manifestation of locality) that the symmetry should preserve it. So $S^1$ with large enough $R$ has single vacuum, which contradicts with a nontrivial projective phase.
More generally, if a discrete symmetry is spontaneously broken,
there can be multiple vacua in the $R\to \infty$ limit.
However, if there is a domain wall connecting the two vacua , there is a exponentially suppressed 
amplitude between the two state with finite but large $R$.
Therefore, we expect that, without additional mechanism prohibiting domain walls[^one_form], there is a single vacuum on $S^1$ with large but finite $R$. 
As the projective phase is discrete, captured by $H^2(G)$, it has to be constant of $R$. Therefore we do not expect any nontrivial projective phase of $U$ acting on $\mathcal{H}_{S^1}$ for any radius $R$ of $S^1$.

[^one_form]: The mechanism is the "one-form symmetry" [@Komargodski:2020mxz]. An older reference is [@Hellerman:2006zs].

--- 
#Discarding the following original version and specialize to the case of $S^1$.
#A reader might have guessed that, as a generalization of what we have learned in the case of QM, the unitary operator realizing the symmetry on $\mathcal{H}_{M_d}$ might have projective phase in there multiplication rule.
#This very natural guess, however, is not correct.
#(This section is a bit abstract, but we will turn to more concrete example soon.)
#
#For a symmetry to be preserved in the theory, we demanded $[U,T_{\mu\nu}] = 0$. This means that the symmetry operator $U$ can commute with a time evolution operator with a small perturbation $\delta g$ of the metric around the flat one, see Figure \@ref(fig:UGeometry) (a), since $T_{\mu\nu}$ couples with $\delta g$.
#A (potentially) stricter requirement is that $U$ commute with time evolution with very bumpy metric: Figure \@ref(fig:UGeometry) (b).
#Or, one might even demand that $U$ commutes with *topology changing* time evolution: Figure \@ref(fig:UGeometry) (c).
#
#The discrepancy among (a),(b) and (c) of Figure \@ref(fig:UGeometry) should be understood as the *mixed anomaly* between the symmetry transformation and the space time symmetry generated by $T_{\mu\nu}$. 
#A nontrivial fact is that there is no such mixed anomaly in 1+1-dimensional unitary bosonic QFT. 
#For this fact, lacking any of the three adjectives gives a counter example, so this is subtle and beyond the scope of this lecture.[^counter]
#Here let us simply assume that the condition (c) in Figure \@ref(fig:UGeometry).
#
#[^counter]: For a unitary QFT, if the manifold $M_d$ is a sphere $S^d$ with the trivial spin structure, then \@ref(fig:UGeometry) generally holds [@Freed:2016rqq;@Yonekura:2018ufj]. For a non-unitary (probability non-preserving) QFT, the ghost number $U(1)$ symmetry of the $bc$ ghost is the counter example.
#
#Then, consider in particular the lower figure of Figure \@ref(fig:UGeometry). Here, a single copy of $S^{d-1}$ evolves into the disjoint union $S^{d-1} \sqcup S^{d-1}$.
#If we let $Z_\text{split}$ denote the evolution operator $\mathcal{S^d} = \mathcal{S^d}\otimes \mathcal{S^d}$, the assumption we have made states
#\begin{equation}
#    (\#eq:UZ)
#    Z_\text{split} U = (U\otimes U) Z_\text{split}.
#\end{equation}
#Now, if we have to elements of the symmetry group $g_1,g_2$ and corresponding unitaries $U_{g_1}, U_{g_2}$, we worry about the
#potential projective phase in the multiplication : $U_{g_1}U_{g_2} = e^{\alpha(g_1,g_2)}U_{g_1g_2}$. However, \@ref(eq:UZ) tells
#\begin{equation*}
#    Z_\text{split} U_{g_1}U_{g_2} = (U_{g_1}U_{g_2}\otimes U_{g_1}U_{g_2}) Z_\text{split}.
#\end{equation*}
#If there were a projective phase, the amount of the phase differs between the left and right hand side. Therefore there is no projective phase of the symmetry operators acting on $\mathcal{H}_{S^d}$. ($Z_\text{split}$ is nonzero if the QFT is unitary.)
---

Then, is there any projective-ness in the symmetry in 2d QFT?
To explicitly see that, we need to think about *manifolds with boundaries*.[^twist]

[^twist]: Instead one can see it from closed manifold with symmetry twist. Actually this is more conventional way. However KO finds that the manifolds with boundary is more "clean" in a sense.


## 1+1-dimensional periodic scalar theory
Rather than explaining the general theory of a QFT on a open manifold, let us jump to a concrete example: 1+1-dimensional (relativistic) massless periodic scalar $\phi$.
The theory should be explained in any good textbooks on string theory, e.g. @PolchinskiVol1. Here we give a lightening review.

### The model
The action of the free massless periodic scalar theory (on the Minkowski flat space) is (in Polchinski's normalization, in particular $\hbar =1$  as usual)
\begin{equation}
    (\#eq:SX)
    S = -\frac{1}{4\pi\alpha'}\int_{M_2} \mathrm{d}\tau\mathrm{d}\sigma \,\eta^{ab}\partial_a X \partial_b X.
\end{equation}
The scalar field $X$ is periodic and we set the periodicity to be $2\pi R$: $X \sim X + 2\pi R$. 
The equation of motion is the massless Klein-Gordon one
\begin{equation}
    (\#eq:EOMX)
    \partial^2 X = 0.
\end{equation}
The canonical momentum $\Pi(\sigma,\tau)$ is
\begin{equation}
    (\#eq:momentum)
    \Pi = \frac{1}{2\pi \alpha'} \partial_\tau X,
\end{equation}
and the Hamiltonian is
\begin{equation}
    (\#eq:HamX)
    H = \frac{1}{2\pi\alpha'}\int\, \mathrm{d}\sigma \delta^{ab}\partial_a X \partial_b X.
\end{equation}

### Quantization on $S^1$ and $U(1)^2$ symmetry
Let us quantize the theory on $S^1$, where we set the periodicity of the spacial coordinate $\sigma \sim \sigma + 2\pi$.
We write the general solution to the EOM \@ref(eq:EOMX) as
\begin{equation}
    (\#eq:Xexp)
    X^w(\sigma,\tau) = x +  R w \sigma + 2\pi \alpha' p \, \tau + \mathrm{i}\bigl(\frac{\alpha'}{2}\bigr) \sum_{m = -\infty}^{\infty} \frac1m\Bigl(\frac{\alpha_m}{z^m_+}+\frac{\tilde\alpha_m}{z^m_-}\Bigr),
\end{equation}
where $z = \exp(- \mathrm{i}(\tau \pm \sigma))$.
The second term is possible because both $\sigma$ and $X$ is periodic, and the winding number $w$ is quantized (discretized): $w\in \mathbb{Z}$.
When there is such topologically distinct classical solutions to the EOM exists, we build the Hilbert space $\mathcal{H}_w$ around each solution labeled by $w$, and the take the direct sum $\mathcal{H} = \bigotimes_w \mathcal{H}_w$ as the total Hilbert space.
The canonical commutation relation gives
\begin{equation}
    (\#eq:comu)
    [x,p] = \mathrm{i}, \quad [\alpha_m,\alpha_n] = [\tilde{\alpha}_m,\tilde{\alpha}_n] = m \delta_{m,-n},
\end{equation}
and the Hamiltonian is (up to a divergent constant coming from commuting $\alpha$'s)
\begin{equation}
    (\#eq:HamXModes)
    H = \frac{\alpha'}{4} \bigl(\frac{n^2}{R^2}+\frac{w^2 R^2}{\alpha'^2}\bigr) + \sum_{n=1}^{\infty} \bigl(\alpha_{-n}\alpha_n + \tilde{\alpha}_{-n}\tilde{\alpha}_n\bigr),
\end{equation}
where $n = R p$ is the quantized momentum whose eigenvalues takes in $\mathbb{Z}$, as in the case of the particle on $S^1$.
A general eigenstate can be constructed by acting finite number of operators $\alpha_{-i}$ and $\tilde{\alpha}_{-j}$ on a state $\ket{n,w}$:
\begin{equation}
    (\#eq:eigen)
    \alpha_{-i_1}^{t_1}\alpha_{-i_2}^{t_s} \cdots 
    \tilde\alpha_{-j_1}^{s_1}\tilde\alpha_{-j_2}^{s_2} \cdots 
    \ket{n,w},
\end{equation}
where $i_a,j_b,t_c,s_d$ are positive integers, and the state $\ket{n,w}$ satisfies
\begin{align}
    \alpha_i \ket{n,w} = \tilde{\alpha}_j \ket{n,w} = 0,
\end{align}
and has the corresponding quantum number $n$ and $w$.

This system famously have to $U(1)$ symmetries, whose charges are $n$ and $w$ respectively. The former is called the momentum $U(1)$, and the latter called the winding $U(1)$.
We write the corresponding unitaries as $U^p_\lambda$ and $U^w_\lambda$, where $\lambda$ is the parameter of the symmetry transformation, so that
\begin{equation}
    (\#eq:UpwAct)
    U^p_\lambda \ket{n,w} = e^{\mathrm{i}\lambda n }\ket{n,w},\quad
    U^w_\lambda \ket{n,w} = e^{\mathrm{i}\lambda w }\ket{n,w}.
\end{equation}
Also, the momentum $U(1)$ is basically the canonical momentum $p$ to the average coordinate $x = \int X \mathrm{d}\sigma$, it causes the translation in the space of $X$:
\begin{equation}
    (\#eq:UpActX)
    (U^p_{\lambda})^\dagger\, f(X(\sigma,\tau)) \, U^p_{\lambda} = 
    f(X(\sigma,\tau) + \lambda R),
\end{equation}
where $f$ is a periodic function.
With this boundary condition, 


### Projective phases on the Hilbert spaces on an interval
Now let us see how the two $U(1)$ symmetries acts on the Hilbert spaces defined on a manifold with boudnaries. In 1d, there is only one (topology type) of a compact manifold with boundaries: the interval $I = [0,2\pi]$.
To define the theory on the interval, we have to pick boundary conditions for each of the boundaries: $\sigma =0$ (left boundary) and $\sigma =2\pi$ (right boundary).
Here we pick the Dirichlet boundary condition $\mathcal{D}(\theta_L)$ and $\mathcal{D}(\theta_R)$ for the left and right boundaries,
defined by 
\begin{equation}
    (\#eq:Dirichlet)
    X(\sigma = 0,t) = R \theta_L, \quad X(\sigma = 2\pi, t)= R \theta_R.
\end{equation}
The expansion of the periodic field $X$ in this case is 
\begin{equation}
    (\#eq:XexpDirichlet)
    X = R\theta_L + R w \sigma + \mathrm{i}\bigl(\frac{\alpha'}{2}\bigr) e^{-\mathrm{i}\tau} \sum_{m = -\infty}^{\infty}  \frac1m \alpha_m \sin(m \sigma/2),
\end{equation}
where the winding $w$ now has to takes values in $w \in (\theta_R-\theta_L)/2\pi + \mathbb{Z}$.
We write the Hilbert space of states on the interval with the boundary condition $\mathcal{D}(\theta_L,\theta_R)$ as $\mathcal{H}_{\theta_L,\theta_R}$, and the state with winding $w$ in it as $\ket{w}_{\theta_L,\theta_R}$. We only consider the ground states for the oscillation modes but the story can be applied to the states with these modes without any change.

How does the $U(1)^2$ symmetries acts on the states?
The momentum symmetry translate $X$, and breaks the boundary condition \@ref(eq:Dirichlet). 
But it still defines a linear map *between the Hilbert spaces*:
\begin{align}
    (\#eq:UpactDirichlet)
    U^p_\lambda : \mathcal{H}_{\theta_L,\theta_R} &\to \mathcal{H}_{\theta_L+\lambda,\theta_R+\lambda}\\
    \ket{w}_{\theta_L,\theta_R} &\mapsto \ket{w}_{\theta_L+\lambda,\theta_R+\lambda}.
\end{align}
On the other hand, the winding $U(1)$ symmetry preserves the Dirichlet boundary condition and the naive extension of the action \@ref(eq:UpwAct) to this case is
\begin{align}
    (\#eq:tildeUwactDirichlet)
    \widetilde{U}^w_\lambda : \mathcal{H}_{\theta_L,\theta_R} &\to \mathcal{H}_{\theta_L,\theta_R}\\
    \ket{w}_{\theta_L,\theta_R} &\mapsto e^{\mathrm{i}\lambda w}\ket{w}_{\theta_L,\theta_R}.
\end{align}
Here we put the tilde on $U^w_\lambda$ because there is one problem with this action, i.e. $\widetilde{U}^w_\lambda = e^{\mathrm{i}(\theta_R-\theta_L)}\widetilde{U}^w_{\lambda+2\pi}$.
This projective phase can be easily removed by redefining the unitary as
\begin{align}
    (\#eq:UwactDirichlet)
    U^w_\lambda : \mathcal{H}_{\theta_L,\theta_R} &\to \mathcal{H}_{\theta_L,\theta_R}\\
    \ket{w}_{\theta_L,\theta_R} &\mapsto e^{\mathrm{i}\lambda (w+(\{\theta_L\}-\{\theta_R\})/2\pi)}\ket{w}_{\theta_L,\theta_R},
\end{align}
where $\{\theta\}$ is the number in $[0,2\pi)$ and $\{\theta\} = \theta \mod 2\pi$.
We use this notation to emphasize that the boundary condition $\mathcal{D}(\theta)$ and $\mathcal{D}(\theta+2\pi)$ are identified in equations e.g. \@ref(eq:UpactDirichlet).
 Note that the modification is not $\{\theta_L-\theta_R\}$, so that the modification is defined *locally* -- it is a sum of independent contributions from the left and right boundaries.
However, this redefinition produces a projective phase in the product of $U^p_{\lambda_p}$ and $U^w_{\lambda_w}$:
\begin{equation}
    (\#eq:UpUwcomu)
    U^w_{\lambda_w}U^p_{\lambda_p}|_{\theta_L,\theta_R} = e^{\mathrm{i}\lambda_w(-[\lambda_p+\theta_R] + [\lambda_p+\theta_L])/2\pi} U^p_{\lambda_p}U^w_{\lambda_w}|_{\theta_L,\theta_R},
\end{equation}
where $[\theta] = \theta - \{\theta\} \in 2\pi \mathbb{Z}$.
The $|_{\theta_1,\theta_2}$ denotes the boundary conditions on which the operator just left of the vertical bar acts. For the other operator composed with this one, the domain is chosen so that the composition makes sense.
This is the projective phase characterizing the mixed anomaly between the two $U(1)$ symmetry (or, the anomaly for the (anti-)diagonal of $U(1)$'s).
This characterization is utterly different from what you find in @PolchinskiVol1, so

::: {.exercise}
Find the relation ship between the characterization of the $U(1)^2$ anomaly here and more traditional one, defined by the 2-pt function of the currents. (KO does not know the answer, and he will be very pleased if you send an answer to him.)
:::

An advantage of this way of stating the anomaly is

1. it is clear that this is some kind of generalization of Wigner's projective phase, and
2. applicable to discrete case.

For example, we can take the $\mathbb{Z}_2$ subgroup of the diagonal of $U(1)$'s whose unitary is $U_{\mathbb{Z}_2}=U^w_\pi U^p_\pi$ and then the projective phase is
\begin{equation}
    (\#eq:2dUZ2)
    U_{\mathbb{Z}_2}^2|_{\theta_L,\theta_R} = e^{\mathrm{i}(-[\pi+\theta_R]+[\pi+\theta_L])/2}\mathrm{id}|_{\theta_L,\theta_R}.
\end{equation}

Next we see that this projective phase can be captured by the third group cohomology.


## Third group cohomology
### Projective phases on Hilbert spaces on intervals
Consider a 1+1-dimensional theory with boundary conditions $\mathcal{B}_i$
and symmetry $G$. 
For each pair of boundary conditions $(\mathcal{B}_L,\mathcal{B}_R)$, we have the Hilbert space $\mathcal{H}_{\mathcal{B}_L,\mathcal{B}_R}$ (for a fixed length of the interval).
A boundary condition $\mathcal{B}$ does not necessarily fixed by the symmetry action, but rather mapped to another boundary condition $g\mathcal{B}$. 
Accordingly, the Unitary in general maps a Hilbert space to another Hilbert space[^separable][^category]:
\begin{equation}
    (\#eq:UgB)
    U_g|_{\mathcal{B}_L,\mathcal{B}_R} : \mathcal{H}_{\mathcal{B}_L,\mathcal{B}_R} \to \mathcal{H}_{g\mathcal{B}_L,g\mathcal{B}_R}.
\end{equation}
Then, the composition rule of $U_g's$ might involve projective phases:
\begin{equation}
    (\#eq:UBproj)
    U_{g_1}U_{g_2}|_{\mathcal{B}_L,\mathcal{B}_R} = e^{\mathrm{i}\tilde{\alpha}(g_1,g_2,\mathcal{B}_L,\mathcal{B}_R)}U_{g_1g_2}|_{\mathcal{B}_L,\mathcal{B}_R}.
\end{equation}
We further assume that the phase is *local*; it should be a sum of contributions from left and right boundaries, and the two contributions should  obey the same rule:
\begin{equation}
    (\#eq:alphasplit)
    \tilde{\alpha}(g_1,g_2,\mathcal{B}_L,\mathcal{B}_R)
    =
    \hat{\alpha}(g_1,g_2,\mathcal{B}_L) - \hat{\alpha}(g_1,g_2,\mathcal{B}_R)
\end{equation}
for some function $\hat\alpha$. The negative sign is because the orientation is reversed between the left and right boundaries; in other words the contribution from the right boundary should be the time-reversal of the one from the left.
In particular, we assume $\tilde{\alpha}(g_1,g_2,\mathcal{B},\mathcal{B}) = 0$. As this can also be considered as the IR cutoff of $\mathbb{R}$ when the interval is long, this should indeed vanish according to the assumptions we made in Section \@ref(noproj).

We also consider the ambiguity of the unitary.
In this case we also demand that the phase redefinition of the unitary is *local* and should looks like
\begin{equation}
    (\#eq:UBbeta)
    U_g|_{\mathcal{B}_L,\mathcal{B}_R} \mapsto e^{\mathrm{i}(\hat\beta(g,\mathcal{B}_L)-\hat\beta(g,\mathcal{B}_R))} U_g|_{\mathcal{B}_L,\mathcal{B}_R}
\end{equation}
for some function $\hat\beta$.

[^separable]: Of course all the separable Hilbert spaces are isomorphic but identifying all of the Hilbert spaces $\mathcal{H}_{\mathcal{B}_L,\mathcal{B}_R}$ by this universal isomorphism is just confusing and of no use.

[^category]: When the theory is a TQFT, there is a multiplication between the state in $\mathcal{H}_{\mathcal{B}_L,\mathcal{B}_M}$ and $\mathcal{H}_{\mathcal{B}_M,\mathcal{B}_R}$ valued in $\mathcal{H}_{\mathcal{B}_L,\mathcal{B}_R}$. You can regard this structure as a **category**, whose objects are the boundary conditions, and morphisms are states on intervals (equivalently, topological boundary-changing operators).
Then $U_g$ is a self-functor on this category, defining **categorical representation** of the (suspension of the) group $G$. 
However the composition rule of the functors is up to natural transformations, which are the projective phases.
When the theory is a general QFT there is no canonical multiplication among the states but there is a *family* of multiplications. In such cases KO imagines that the boundary conditions would define a category over some operad (something like the swiss-cheese one), and we should be dealing with the representation theory valued in such categories.
As far as the anomaly is concerned, the only thing for which we need the operad-category structure is to show the splitting \@ref(eq:alphasplit).
In higher dimensional QFTs, the category also has to be higher.

### Group cohomology
Now let us see that the projective phase \@ref(eq:UBproj), subject to the splitting \@ref(eq:alphasplit) and the ambiguity \@ref(eq:UBbeta), defines a group cohomology.
First, we fix a simple boundary condition $\mathcal{B}_0$, define a 3-cochain $\alpha \in C^3(G)$ by
\begin{equation}
    (\#eq:alphadef)
    \alpha(g_1,g_2,g_3) = \tilde{\alpha}(g_1,g_2,g_3\mathcal{B}_0,\mathcal{B}_0) = \hat\alpha(g_1,g_2,g_3\mathcal{B}_0) - \hat\alpha(g_1,g_2,\mathcal{B}_0).
\end{equation}
A boundary condition is called simple when it cannot be written as a direct sum of two boundary conditions.[^non-simple]
For a non-simple boundary conditions the projective "phase" can take different values for each of the simple components and actually be a diagonal matrix.
From this definition, we have
\begin{equation}
    (\#eq:alphatildealpha)
    \tilde{\alpha}(g_1,g_2,g_3\mathcal{B}_0,g_4\mathcal{B}_0) =     
    \alpha(g_1,g_2,g_3) - \alpha(g_1,g_2,g_4).
\end{equation}
Now let us examine the associativity of $U_{g_1}U_{g_2}U_{g_3}|_{g_4\mathcal{B}_0,\mathcal{B}_0}$. 
One way of composing it is 
\begin{align}
    (\#eq:associative1)
    U_{g_1}(U_{g_2}U_{g_3})|_{g_4\mathcal{B}_0,\mathcal{B}_0}
    &= e^{\mathrm{i}(\alpha(g_2,g_3,g_4))}U_{g_1}U_{g_2g_3}|_{g_4\mathcal{B}_0,\mathcal{B}_0}\\
    &= e^{\mathrm{i}(\alpha(g_2,g_3,g_4)+\alpha(g_1,g_2g_3,g_4))}U_{g_1g_2g_3}|_{g_4\mathcal{B}_0,\mathcal{B}_0},
\end{align}
while the other is
\begin{align}
    (\#eq:associative2)
    (U_{g_1}U_{g_2})|_{g_3g_4\mathcal{B}_0,g_3\mathcal{B}_0}U_{g_3}|_{g_4\mathcal{B}_0,\mathcal{B}_0}
    &= e^{\mathrm{i}(\alpha(g_1,g_2,g_3g_4)-\alpha(g_1,g_2,g_3))}U_{g_1g_2}U_{g_3}|_{g_4\mathcal{B}_0,\mathcal{B}_0}\\
    &= e^{\mathrm{i}(\alpha(g_1,g_2,g_3g_4)-\alpha(g_1,g_2,g_3)+\alpha(g_1g_2,g_3,g_4))}U_{g_1g_2g_3}|_{g_4\mathcal{B}_0,\mathcal{B}_0}.
\end{align}
Thus, the associativity demands
\begin{align}
    (\#eq:3cocycle)
    0 = (\delta_4 \alpha) (g_1,g_2,g_3,g_4) = &\alpha(g_2,g_3,g_4) + \alpha (g_1,g_2g_3,g_4) \\&- \alpha(g_1,g_2,g_3g_4) + \alpha(g_1,g_2,g_3) - \alpha(g_1g_2,g_3,g_4).
\end{align}
Also, the ambiguity \@ref(eq:UBbeta) causes the shift to $\alpha$ by,
\begin{equation}
    (\#eq:3coboundary)
    \alpha(g_1,g_2,g_3 )\to \alpha(g_1,g_2,g_3) + (\delta_3 \beta)(g_1,g_2,g_3)
\end{equation}
where $\beta(g_1,g_2) = \hat\beta(g_1,g_2\mathcal{B}_0) - \hat\beta(g_1,\mathcal{B}_0)$ and $\delta_3$ is the one we defined before in \@ref(eq:cocycle).

[^non-simple]: A non-simple boundary condition $\mathcal{B}_1\oplus \mathcal{B}_2$ is like having a external qubit sitting on the boundary which switches the two boundary conditions. Being external means that the state of the qubit cannot be affected by the dynamics of the system. So, e.g. in a spin system, the direct sum over the fixed boundary conditions (which is non-simple) is not the same as the free boundary condition (which is simple).

::: {.exercise}
Check that $\delta_4\circ \delta_3 = 0$.
:::

Now the we define the 3rd cohomology in the same we did for the second cohomology:
\begin{equation}
    (\#eq:H3g)
    H^3(G) = \mathrm{Ket}(\delta_4)/\mathrm{Im}(\delta_3).
\end{equation}
This is the invariant information from the projective phases associated to the Hilbert spaces on intervals.

::: {.exercise}
Calculate $H^3(\mathbb{Z}_2)$.
:::


### Anomaly-BC relationship
In the above definition \@ref(eq:3cocycle), $\alpha$ depends on the choice of $\mathcal{B}_0$. So is this projective phase a property of the boundary condition, rather than a theory?
The answer is no, the cohomology class of the projective phase should be uniform over the boundary conditions of a fixed theory.
To see this, we assume that the boundary conditions admits a sum so that $\mathcal{H}_{\mathcal{B}_1\oplus \mathcal{B}_2,\mathcal{B}_R} = \mathcal{H}_{\mathcal{B}_1,\mathcal{B}_R} \oplus \mathcal{H}_{\mathcal{B}_2,\mathcal{B}_R}$.
The boundary condition $\mathcal{B}_1\oplus \mathcal{B}_2$ is like 
putting a qubit entangled with the boundary condition (e.g. the value of $X(0)$ in the periodic scalar example).
Then, we also want the symmetry $U_g$ acts on $\mathcal{H}_{\mathcal{B}_1\oplus \mathcal{B}_2,\mathcal{B}_R}$.
However if the cohomology classes associated to $\mathcal{B}_1$ and $\mathcal{B}_2$ were different, the projective "phase" on this direct sum space is not a overall phase, but just a diagonal matrix not proportional to the identity. This breaks the assumption that the symmetry is $G$.
Therefore, the cohomology class is the **property of the theory**, not the boundary condition, and you can calculate it by picking any boundary condition you like.

This leads to the following theorem, first claimed by @Thorngren:2020yht [^simeon]:

::: {.theorem}
If there is a simple boundary condition $\mathcal{B}$ such that $g \mathcal{B} =\mathcal{B}$ for elements of a symmetry group $g\in G$, this symmetry $G$ is non-anomalous, i.e. the cohomology class is trivial.
(This hold for a QFT in a general dimensions.)
:::
Indeed by the definition \@ref(eq:alphadef) $\alpha = 0$ by choosing $\mathcal{B}_0 = \mathcal{B}$ in such a case.[^Thorngren]

---
# Have to think about the simplicity! Maybe the reasoning above for the unimormity of the phase is not correct and we rather refer to the renormalization group.
---

[^simeon]: See also @Hellerman:2021fla.
[^Thorngren]: The work by @Thorngren:2020yht is not this trivial, as their definition of the anomaly is different from us.

## Prospects
### Background formalism
### Higher diemnsions
### Fermions



