--- 
title: "Topological Aspects of Symmetry in Low Dimensions"
author: "Kantaro Ohmori"
affiliation: "University of Tokyo"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: scrartcl
bibliography: [ref.bib]
#biblio-style: apalike
link-citations: yes
github-repo: kantohm11/symmetry_review
description: ""
abstract: |
  This is a lecture note prepared for <a href="https://sites.google.com/view/apctpwinterschool/program">"26th APCTP Winter School on Fundamental Physics"</a>, Feb. 14-18, 2022.
  
  In this lecture we will study the symmetry and its anomaly in low-dimensional, i.e. 0+1d and 1+1d, quantum field theories.
  In 0+1-dimensional quantum field theory, a.k.a quantum mechanics, the Wigner’s theorem tells that a global symmetry forms a group and acts on the Hilbert (state) space as a projective representation. We will see example with non-trivial projective phases and how it can be related to symmetry protected topological phases in 1+1-dimensions. We then see how the story are generalized/changed in 1+1-dimensional (relativistic) quantum field theory, where the locality of the theory plays an important role.
  Time permits, we also see how the inclusion of fermions affects the story.
---

# Introduction
Symmetry is a guiding principle in physics. In many case, given a system, you first analyze its symmetry. Or, to model a given phenomena, the symmetry is often be the first clue.
Therefore, there have been numerous research on the topic. What is surprising is that, still, in 2022, it is a hot area of research and there are many things to be understood.

## Aim
This lecture aims to be an introduction to the field of symmetry and its anomaly in quantum field theory. In the first part of the lecture topological aspects of symmetry in quantum mechanics are reviewed, then in the latter part of the lecture we proceed to symmetry in 1+1-dimensional quantum field theory.

Proficiency in the undergraduate level quantum mechanics and some basic knowledge about quantum field theory are assumed, but (hopefully) not much more. Especially, the first half will focus on quantum mechanics so it is hopefully understandable to even advanced undergraduates.

## Useful references
1. @tachikawa_2019:
  The first half of Yuji’s lecture is about the big framework the most of researchers assume (but not necessarily proven), which I will omit.
  The second half of Yuji's will serve as an advanced version of this lecture.
2. @Witten:2015aoa, @Witten:2015aba:
  While there are not so much overlap between this lecture by me and these lecture note and paper by E. Witten, and Witten's is a bit more advanced, they are undoubtedly ones of the best entry points to the field.